// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using Popper.Utilities;
using UIKit;

namespace Popper
{
    public partial class BasicViewController : UIViewController
    {
        CGRect BoxFrame;

        public BasicViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            animationView.Layer.CornerRadius = Constants.DefaultBoxEdge / 4;
            InitBox();
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            InitButtons();
        }

        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);
            button1.TouchUpInside -= Button1TouchUpInside;
        }

        void InitButtons()
        {
            button1.TouchUpInside += Button1TouchUpInside;
        }

        void Button1TouchUpInside(object sender, EventArgs e)
        {
        }

        void InitBox()
        {
            BoxFrame = animationView.Frame;
        }
    }
}
