// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Popper.Utilities;
using UIKit;

namespace Popper
{
    public partial class CustomTransitionViewController : UIViewController
    {
        public CustomTransitionViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            this.TransitioningDelegate = new CustomTransitioningDelegate(this.View.Frame);
        }
    }
}
