// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Facebook.Pop;
using Foundation;
using UIKit;

namespace Popper
{
    public partial class DecayViewController : UIViewController
    {
        public DecayViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitPanGestureRecognizer();
        }

        void AnimationViewDragged(UIPanGestureRecognizer recognizer)
        {
            var animation = POPDecayAnimation.AnimationWithPropertyNamed(POPAnimation.LayerPosition);
            animation.Velocity = NSValue.FromCGPoint(recognizer.TranslationInView(View));
            animationView.Layer.AddAnimation(animation, "slide");
        }

        void InitPanGestureRecognizer()
        {
            animationView.AddGestureRecognizer(new UIPanGestureRecognizer(recognizer => AnimationViewDragged(recognizer)));
        }
    }
}
