// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Popper
{
    public partial class DestinationViewController : UIViewController
    {
        public DestinationViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NavigationItem.SetHidesBackButton(true, false);
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            PopButton.TouchUpInside += PopButtonTouchUpInside;
        }

        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);
            PopButton.TouchUpInside -= PopButtonTouchUpInside;
        }

        void PopButtonTouchUpInside(object sender, EventArgs e)
        {
            NavigationController.PopViewController(true);
        }
    }
}
