// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Popper
{
    public partial class ModalViewController : UIViewController
    {
        public ModalViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            DismissButton.TouchUpInside += (object sender, EventArgs e) =>
            {
                DismissModalViewController(true);
            };
        }
    }
}
