// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Popper
{
    public partial class OptionsViewController : UIViewController
    {
        NSUserDefaults UserDefaults;

        public OptionsViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            UserDefaults = NSUserDefaults.StandardUserDefaults;
            InitSliders();
        }

        void InitSliders()
        {
            slider1.Value = NSUserDefaults.StandardUserDefaults.FloatForKey("slider1");
            slider2.Value = NSUserDefaults.StandardUserDefaults.FloatForKey("slider2");
            slider3.Value = NSUserDefaults.StandardUserDefaults.FloatForKey("slider3");
            slider4.Value = NSUserDefaults.StandardUserDefaults.FloatForKey("slider4");
            slider5.Value = NSUserDefaults.StandardUserDefaults.FloatForKey("slider5");


            slider1.ValueChanged += (object sender, EventArgs e) =>
            {
                var slider1 = ((UISlider)sender).Value;
                UserDefaults.SetFloat(slider1, "slider1");
            };

            slider2.ValueChanged += (object sender, EventArgs e) =>
            {
                var slider2 = ((UISlider)sender).Value;
                UserDefaults.SetFloat(slider2, "slider2");
            };

            slider3.ValueChanged += (object sender, EventArgs e) =>
            {
                var slider3 = ((UISlider)sender).Value;
                UserDefaults.SetFloat(slider3, "slider3");
            };

            slider4.ValueChanged += (object sender, EventArgs e) =>
            {
                var slider4 = ((UISlider)sender).Value;
                UserDefaults.SetFloat(slider4, "slider4");
            };

            slider5.ValueChanged += (object sender, EventArgs e) =>
            {
                var slider5 = ((UISlider)sender).Value;
                UserDefaults.SetFloat(slider5, "slider5");
            };
        }
    }
}
