// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Facebook.Pop;
using Foundation;
using UIKit;

namespace Popper
{
    public partial class PopViewController : UIViewController
    {
        float SizeX;
        float SizeY;

        public PopViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitButtons();
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            GetUserDefaults();
        }

        void GetUserDefaults()
        {
            SizeX = NSUserDefaults.StandardUserDefaults.FloatForKey("slider1");
            SizeY = NSUserDefaults.StandardUserDefaults.FloatForKey("slider2");
        }

        void BoxAnimation()
        {
            var animation = POPSpringAnimation.AnimationWithPropertyNamed(POPAnimation.LayerBounds);
            animation.ToValue = NSValue.FromCGRect(new CGRect(0, 0, SizeX, SizeY));
            animationView.Layer.AddAnimation(animation, "size");
            View.SetNeedsLayout();
        }

        void InitButtons()
        {
            button1.TouchUpInside += (object sender, EventArgs e) =>
            {
                BoxAnimation();
            };
        }
    }
}
